<?PHP
date_default_timezone_set('Asia/Taipei');//設置時區
session_start();
header('Content-type:text/html;charset=utf-8');
define("DB_HOST","localhost");
define("DB_USER","root");
define("DB_PASSWORD","0926");
define("DB_DATABASE","firstmb");
define("DB_PORT",3306);

//date_default_timezone_set('Asia/Taipei');//設置時區
//session_start();
//header('Content-type:text/html;charset=utf-8');
//define("DB_HOST","192.168.2.200");
//define("DB_USER","philhaoc_ab11");
//define("DB_PASSWORD","123456789");
//define("DB_DATABASE","philhaoc_mb");
//define("DB_PORT",3306);
?>